"""Deterministic raw-waveform fixtures, never a source of inference labels."""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
from scipy.io import wavfile
from scipy.signal import fftconvolve
from .signals import generate_probe

SCENARIOS=('room','partial','coplanar','null','clutter','mismatch','reflector','warp','four_views')


def simulate_session(output_dir, scenario='room', seed=1, capture_count=None):
    if scenario not in SCENARIOS:
        raise ValueError(f'unknown scenario {scenario}; choose {SCENARIOS}')
    if capture_count is not None and (not isinstance(capture_count,int) or isinstance(capture_count,bool) or not 4 <= capture_count <= 24):
        raise ValueError('capture_count must be an integer from 4 to 24')
    root=Path(output_dir)
    root.mkdir(parents=True,exist_ok=True)
    rng=np.random.default_rng(seed)
    x,probe=generate_probe()
    fs=probe['sample_rate_hz']; c=343.; source=np.array([2.1,1.7,1.25])
    # Noncoplanar asymmetric surveyed microphone stops, grouped into two 4-phone placements.
    receivers=np.array([[.85,.95,.7],[3.65,.7,1.65],[4.6,3.4,.85],[1.1,3.65,2.25],
                        [2.75,2.95,.45],[4.45,1.85,2.4],[.65,2.15,1.45],[3.2,3.8,1.9]])
    receivers+=rng.uniform(-.08,.08,receivers.shape)
    dimensions=np.array([5.7,4.6,3.3])+rng.uniform(-.12,.12,3)
    surfaces=[dict(surface_id=f'truth-{axis}-{side}',normal=[int(i==axis) for i in range(3)],
                   offset_m=float(dimensions[axis] if side else 0.)) for axis in range(3) for side in range(2)]
    if scenario=='partial': surfaces=surfaces[1:2]+surfaces[3:4]+surfaces[5:6]
    if scenario in ('null','clutter'): surfaces=[]
    if capture_count is not None:
        if capture_count > len(receivers):
            # Separate stream preserves all original eight frozen waveform fixtures.
            extra_rng=np.random.default_rng(np.random.SeedSequence([int(seed),9124]))
            extra=extra_rng.uniform([.5,.5,.4],dimensions-[.5,.5,.4],size=(capture_count-len(receivers),3))
            receivers=np.vstack([receivers,extra])
        else:
            receivers=receivers[:capture_count]
    if scenario=='coplanar': receivers[:,2]=source[2]
    if scenario=='four_views': receivers=receivers[:4]
    if scenario=='reflector':
        normal=np.array([.8,.35,.487339717]);normal/=np.linalg.norm(normal)
        surfaces.append(dict(surface_id='truth-tilted-reflector',normal=normal.tolist(),offset_m=4.5))
    session=dict(schema_version='1.0',session_id=f'sim-{scenario}-{seed}',sound_speed_m_s=c,
        sound_speed_std_m_s=.6,source_clock_scale=1.,source_clock_std_ppm=100.,
        source_position_m=source.tolist(),source_position_std_m=.01,probe=probe,captures=[])
    truth=dict(schema_version='1.0',scenario=scenario,seed=int(seed),surfaces=surfaces,
        source_position_m=source.tolist(),receiver_positions_m=receivers.tolist(),
        simulation=dict(method='first_order_image_sources_fractional_delay',sample_rate_hz=fs,
                        mismatch=scenario=='mismatch',physical_measurement=False),paths=[])
    x_time=np.arange(len(x))/fs
    for i,receiver in enumerate(receivers):
        direct_distance=float(np.linalg.norm(receiver-source))
        paths=[(direct_distance/c,.6,'direct')]
        for surface in surfaces:
            normal=np.array(surface['normal']);d=surface['offset_m']
            # All points for the selected fixtures share an interior half-space.
            if (source@normal-d)*(receiver@normal-d)<=0: continue
            image=source+2*(d-source@normal)*normal
            length=float(np.linalg.norm(receiver-image))
            # Deliberately no inverse-distance amplitude promise: simple bounded material strength.
            strength=float(rng.uniform(.14,.23))
            paths.append((length/c,strength,surface['surface_id']))
        if scenario=='clutter':
            paths.extend((direct_distance/c+float(t),float(a),'unstructured-clutter') for t,a in zip(rng.uniform(.003,.045,6),rng.uniform(.07,.2,6)))
        if scenario=='mismatch':
            for j in range(4):
                # Weak view-dependent multipath, not generated by fitted first-order planes.
                paths.append((direct_distance/c+float(rng.uniform(.012,.07)),float(rng.uniform(.015,.035)),'late-clutter'))
        alpha=1.+float(rng.uniform(-300,300))*1e-6
        offset=float(rng.uniform(.045,.095))
        u=np.arange(round((len(x)/fs+.3)*fs))/fs
        t=(u-offset)/alpha
        if scenario=='warp': t+=.0015*np.sin(2*np.pi*t/1.1)
        recording=np.zeros(len(u))
        for delay,amplitude,label in paths:
            component=np.interp(t-delay,x_time,x,left=0,right=0)
            if scenario=='mismatch':
                # Frequency coloration and short dispersive transducer response, omitted by solver.
                component=fftconvolve(component,np.array([1.,-.18,.12,-.04]),mode='full')[:len(component)]
            recording+=amplitude*component
        recording+=rng.normal(0,.0007 if scenario=='mismatch' else .00025,len(recording))
        # Fixed attenuation, never clipping-normalize each recording to hide overload.
        recording*=.65
        if np.max(np.abs(recording))>=.98: raise RuntimeError('synthetic overload')
        filename=f'capture-{i:02d}.wav'
        wavfile.write(root/filename,fs,np.round(recording*32767).astype(np.int16))
        session['captures'].append(dict(capture_id=f'capture-{i:02d}',receiver_position_m=receiver.tolist(),
            receiver_position_std_m=.01,recording_path=filename,provenance='simulated',sample_rate_hz=fs))
        truth['paths'].append(dict(capture_id=f'capture-{i:02d}',alpha=alpha,offset_s=offset,
            arrivals=[dict(delay_s=float(delay),amplitude=float(amplitude),surface_id=label) for delay,amplitude,label in paths]))
    wavfile.write(root/'probe.wav',fs,np.round(x*32767).astype(np.int16))
    (root/'session.json').write_text(json.dumps(session,indent=2)+'\n')
    (root/'truth.json').write_text(json.dumps(truth,indent=2)+'\n')
    return root/'session.json'
